name: notes-backend
services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3001:80
    environment:
      - PORT=80
      - MONGODB_URL=mongodb://${NOTES_USER}:${NOTES_PASSWORD}@notes-db/${NOTES_DB}
    depends_on:
      - notes-db
    networks:
      - notes-net
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
  notes-db:
    image: mongodb/mongodb-community-server:7.0.11-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: notes-data
        target: /data/db
    networks:
      - notes-net

volumes:
  notes-data:
networks:
  notes-net:
